name: This workflow contains usage of the context variables with in the workflow.

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Using configuration variable
        run: |
          echo Repository name - ${{ github.repository }}
          echo Workflow name -  ${{ github.workflow }}
          echo "Triggered By - ${{ github.triggering_actor }}"
          echo "Triggered By - ${{ github.actor }}"
          echo "Github Ref - ${{ github.ref }}"
          echo "Event - ${{ github.event_name }}"
          echo "Github SHA - ${{ github.sha }}"

