name: This workflow contains usage of the variables with in the workflow.

on:
  push:
    branches: ["main"]

  workflow_dispatch:

env:
  name: Shreyansh Jain
  skill: Github Actions

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Using Variables defined using env
        run: echo $name has the knowledge of $skill

