name: This workflow contains usage of the variables with in the workflow.

on:
  push:
    branches: ["main"]

  workflow_dispatch: # manual trigger

env:
  name: Shreyansh Jain
  skill: Github Actions

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      background: IT

    steps:
      - uses: actions/checkout@v4

      - name: Using Variables defined using env
        run: |
          echo $name has the knowledge of $skill and he is from $background
          echo Current Year: $Year
        env:
          Year: 2025

